[package]
name = "cargo-bitbake"
version = "0.3.0"
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/cardoe/cargo-bitbake"
homepage = "https://github.com/cardoe/cargo-bitbake"
documentation = "https://github.com/cardoe/cargo-bitbake"
readme = "README.md"
keywords = ["cargo-subcommand", "bitbake", "yocto", "recipe"]
description = """
Generates a BitBake recipe for a package utilizing meta-rust's classes.
"""

[dependencies]
cargo = "^0.10"
itertools = "^0.5.0"
rustc-serialize = "^0.3"
