[package]
name = "cargo-bitbake"
version = "0.2.0"
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/cardoe/cargo-bitbake"
homepage = "https://github.com/cardoe/cargo-bitbake"
readme = "README.md"
description = """
Generates a BitBake recipe for a package utilizing meta-rust's classes.
"""

[dependencies]
cargo = "^0.10"
rustc-serialize = "^0.3"
